version: "3.1"

services:
  engine:
    image: qlikcore/engine:${ENGINE_VERSION}
    command: |
      -S AcceptEULA=${ACCEPT_EULA}
      -S SSEPlugin=sse,sse-cluster:50051
    ports:
      - "9076:9076"
    depends_on:
      - sse
  sse:
    build:
      context: ./sse
      dockerfile: Dockerfile
    container_name: "sse-cluster"
    ports:
      - "50051:50051"
